# executable files for this directory
OBJECTS = test.out count_int.out

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

