# executable files for this directory
OBJECTS = word_transform.out 101.out learn_set.out delete_s.out learn_multimap.out

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

