DIRS = chaper10 chaper11 chaper12

all:  
	cd chaper10;make
	cd chaper11;make
	cd chaper12;make

clean: 
	cd chaper10; make clean 
	cd chaper11; make clean 
	cd chaper12; make clean 

clobber: 
	cd chaper10; make clobber 
	cd chaper11; make clobber 
	cd chaper12; make clobber 

tags:
	cd chaper10; make tags
	cd chaper11; make tags	
	cd chaper12; make tags	
