# executable files for this directory
OBJECTS = person/person_test.out X_and_Y/X_and_Y_test.out mutable_test.out
#person_test.out: person/person.cpp person/test.cpp
#	g++ -o person/person_test.out person/person.cpp person/test.cpp
#X_and_Y_test.out: X_and_Y/x_and_y.h  X_and_Y/test.cpp
#	g++ -o X_and_Y/X_and_Y_test.out X_and_Y/x_and_y.h X_and_Y/test.cpp
# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
