DIRS = cpp_primer pointers_on_c

all:  
	cd cpp_primer; make 
	cd pointers_on_c; make 

clean: 
	cd cpp_primer; clean 
	cd pointers_on_c; clean 

clobber: 
	cd cpp_primer; clobber 
	cd pointers_on_c; clobber 

tags:
	cd cpp_primer; tags 
	cd pointers_on_c; tags 
